import Head from "next/head";
import LeftSidebar from "../components/LeftSidebar";
import Hero from "../components/Hero.js";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex">
        <LeftSidebar />
        <div className="flex-1">
          <Hero />
        </div>
      </div>
    </div>
  );
};
